### ISSUE TITLE
Very low PPS for correlated data

### ISSUE THREAD

**Issue by py9mrg** [paulvanderlaken/ppsr#13]
Hello,

I'm having a bit of a weird result where the scores are essentially all zero, despite the fact there are clearly some correlations. Maybe a problem of my understanding of PPS, or a gremlin in the calculation. Here's a reprex:

``` r
library(ppsr)
library(tibble) # I'm manually providing a simplified real data frame so this makes it easier to type out!

data <- tribble(
  ~varA, ~varB,
  25.000, 0.08,
  20.000, 0.09,
  16.000, 0.08,
  10.000, 0.09,
  5.000, 0.10,
  2.000, 0.12,
  1.000, 0.16,
  0.500, 0.17,
  0.100, 0.25,
  0.045, 0.45
)

cor(data) # clearly (loosely) correlated
#>            varA       varB
#> varA  1.0000000 -0.5852726
#> varB -0.5852726  1.0000000

score_matrix(data) # but very low PPS here??
#>      varA         varB
#> varA    1 1.110223e-16
#> varB    0 1.000000e+00

plot(data$varA, data$varB) # maybe the form of the relationship is a problem?
```

![](https://i.imgur.com/NcwvFWy.png)

``` r
# deliberately subsetting data to a roughly linear portion
reduced_data <- data[data$varA < 5 & data$varA > 0.045, ]

cor(reduced_data) # even better correlation coeff.
#>            varA       varB
#> varA  1.0000000 -0.8949743
#> varB -0.8949743  1.0000000

score_matrix(reduced_data) # even worse PPS!!!
#>      varA varB
#> varA    1    0
#> varB    0    1

plot(reduced_data$varA, reduced_data$varB) # looks linear enough
```

![](https://i.imgur.com/vg4O9Is.png)

<sup>Created on 2021-01-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Is this a problem of data set size and PPS doesn't work well with small data due to using decision trees?

**Comment by paulvanderlaken** [comment]
Hi py9mrg, first of all, thanks for compiling this great reproducible example. This greatly helps me in exploring this issue.

Your "problem" is very much caused by the small data sample. The basic decision tree that is currently trained in the back-end is unable to deal with this small amount of data. It does not form any branches/splits/nodes apart from the root/stump.

In your full dataset, for varA ~ varB, it predicts 0.159 for all cases. For varB ~ varA, it predicts 7.9645 for all cases. This is exactly the same as the naive model that's being used as a benchmark in the backend (it's the average score on the variable). Hence, with your informed prediction having the same MAE as the naive model prediction, you end up with a PPS of (about) 0. 

The same happens in your second example.

In the development branch of the package, I implemented cross-validation, which makes the model performance even worse. Yet, I implemented a warning message if the test-set is smaller than 10 observations. I don't know whether this is the best way forward. 
Also, in the developmental version, score() returns a more detailed overview of the model and naive predictions, thus explaining how we get to the PPS of 0 in your case.

If you would resample your current dataset, you would see what the PPS is like better. 


```
library(ppsr)
library(tibble) # I'm manually providing a simplified real data frame so this makes it easier to type out!

data <- tribble(
  ~varA, ~varB,
  25.000, 0.08,
  20.000, 0.09,
  16.000, 0.08,
  10.000, 0.09,
  5.000, 0.10,
  2.000, 0.12,
  1.000, 0.16,
  0.500, 0.17,
  0.100, 0.25,
  0.045, 0.45
)

# your original results
cor(data)
score_matrix(data)

# the upsampled results
data2 = data[rep(1:nrow(data), 10), ]
cor(data2)
score_matrix(data2)
```

**Comment by py9mrg** [comment]
Hello again,

You're very welcome - I rather think all the thanks ought to go to you and the 8080labs team!

Thanks also for your explanation - I feel a little daft for not having thought to resample the data, so thanks very much for that tip.

I'm really looking forward to going back and analysing some data that was really problematic to find the problem variable that was causing a technical issue.  In the end we solved the problem but I suspect PPS would have allowed us to get to that solution a lot faster - hence wanting to go back and re-examine that data. PPS is a really exciting new paradigm for assessing correlations, so thanks again to you and the 8080labs team.

**Comment by paulvanderlaken** [comment]
No problem, happy to help. And I feel the issue you raise is a valid one, which is not necessarily solved by this resampling I propose. So I will definitely keep this issue in mind in the further development!
Good luck with your further analysis and hope the PPS paradigm is of value in your future projects!
